
export const FETCHING_FACULTIES_STARTED = 'FETCHING_FACULTIES_STARTED';
export const FETCHING_FACULTIES_COMPLETED = 'FETCHING_FACULTIES_COMPLETED';
export const FETCHING_FACULTIES_FAILED = 'FETCHING_FACULTIES_FAILED';

export const FETCHING_MAJORS_STARTED = 'FETCHING_MAJORS_STARTED';
export const FETCHING_MAJORS_COMPLETED = 'FETCHING_MAJORS_COMPLETED';
export const FETCHING_MAJORS_FAILED = 'FETCHING_MAJORS_FAILED';

export const POST_PROJECT_REQUEST_FORM_STARTED = 
'POST_PROJECT_REQUEST_FORM_STARTED';
export const POST_PROJECT_REQUEST_FORM_COMPLETED = 
'POST_PROJECT_REQUEST_FORM_COMPLETED';
export const POST_PROJECT_REQUEST_FORM_FAILED = 
'POST_PROJECT_REQUEST_FORM_FAILED';

export const SELECT_FACULTY = 'SELECT_FACULTY';
export const SELECT_MAJOR = 'SELECT_MAJOR';





