export const FETCHING_STUDENTS_MANAGER_STARTED = 'FETCHING_FACULTIES_STARTED';
export const FETCHING_STUDENTS_MANAGER_COMPLETED = 'FETCHING_STUDENTS_MANAGER_COMPLETED';
export const FETCHING_STUDENTS_MANAGER_FAILED = 'FETCHING_STUDENTS_MANAGER_FAILED';

