export const FETCHING_STUDENTS_MANAGER_STARTED = 'FETCHING_FACULTIES_STARTED';
export const FETCHING_STUDENTS_MANAGER_COMPLETED = 'FETCHING_STUDENTS_MANAGER_COMPLETED';
export const FETCHING_STUDENTS_MANAGER_FAILED = 'FETCHING_STUDENTS_MANAGER_FAILED';

export const ACCEPT_STUDENT_STARTED = 'ACCEPT_STUDENT_STARTED';
export const ACCEPT_STUDENT_COMPLETED = 'ACCEPT_STUDENT_COMPLETED';
export const ACCEPT_STUDENT_FAILED = 'ACCEPT_STUDENT_FAILED';

export const REJECT_STUDENT_STARTED = 'REJECT_STUDENT_STARTED';
export const REJECT_STUDENT_COMPLETED = 'REJECT_STUDENT_COMPLETED';
export const REJECT_STUDENT_FAILED = 'REJECT_STUDENT_FAILED';



