export const FETCHING_REQUESTS_STARTED = 'FETCHING_REQUESTS_STARTED';
export const FETCHING_REQUESTS_COMPLETED = 'FETCHING_REQUESTS_COMPLETED';
export const FETCHING_REQUESTS_FAILED = 'FETCHING_REQUESTS_FAILED';

export const PATCH_REQUEST_APPROVED_STARTED = 'PATCH_REQUEST_APPROVED_STARTED';
export const PATCH_REQUEST_APPROVED_COMPLETED = 'PATCH_REQUEST_APPROVED_COMPLETED';
export const PATCH_REQUEST_APPROVED_FAILED = 'PATCH_REQUEST_APPROVED_FAILED';

export const DELETE_REQUEST_STARTED='DELETE_REQUEST_STARTED';
export const DELETE_REQUEST_COMPLETED='DELETE_REQUEST_COMPLETED';
export const DELETE_REQUEST_FAILED='DELETE_REQUEST_FAILED';

export const PROJECT_REQUEST_SELECTED= 'PROJECT_REQUEST_SELECTED';

export const FETCHING_PROJECT_REQUEST_IMAGES_STARTED='FECHING_PROJECT_REQUEST_IMAGES_STARTED';
export const FETCHING_PROJECT_REQUEST_IMAGES_COMPLETED='FECHING_PROJECT_REQUEST_IMAGES_COMPLETED';
export const FETCHING_PROJECT_REQUEST_IMAGES_FAILED='FECHING_PROJECT_REQUEST_IMAGES_FAILED';

export const FETCHING_PROJECT_REQUEST_LINKS_STARTED='FECHING_PROJECT_REQUEST_LINKS_STARTED';
export const FETCHING_PROJECT_REQUEST_LINKS_COMPLETED='FECHING_PROJECT_REQUEST_LINKS_COMPLETED';
export const FETCHING_PROJECT_REQUEST_LINKS_FAILED='FECHING_PROJECT_REQUEST_LINKS_FAILED';
