export const FETCHING_REQUESTS_STARTED = 'FETCHING_REQUESTS_STARTED';
export const FETCHING_REQUESTS_COMPLETED = 'FETCHING_REQUESTS_COMPLETED';
export const FETCHING_REQUESTS_FAILED = 'FETCHING_REQUESTS_FAILED';




