export const FETCHING_REQUESTS_STARTED = 'FETCHING_REQUESTS_STARTED';
export const FETCHING_REQUESTS_COMPLETED = 'FETCHING_REQUESTS_COMPLETED';
export const FETCHING_REQUESTS_FAILED = 'FETCHING_REQUESTS_FAILED';

export const PATCH_REQUEST_APPROVED_STARTED = 'PATCH_REQUEST_APPROVED_STARTED';
export const PATCH_REQUEST_APPROVED_COMPLETED = 'PATCH_REQUEST_APPROVED_COMPLETED';
export const PATCH_REQUEST_APPROVED_FAILED = 'PATCH_REQUEST_APPROVED_FAILED';

export const DELETE_REQUEST_STARTED='DELETE_REQUEST_STARTED';
export const DELETE_REQUEST_COMPLETED='DELETE_REQUEST_COMPLETED';
export const DELETE_REQUEST_FAILED='DELETE_REQUEST_FAILED';