export const FETCHING_COMPANIES_STARTED = 'FETCHING_COMPANIES_STARTED';
export const FETCHING_COMPANIES_COMPLETED = 'FETCHING_COMPANIES_COMPLETED';
export const FETCHING_COMPANIES_FAILED = 'FETCHING_COMPANIES_FAILED';
