export const FETCHING_COMPANIES_STARTED = 'FETCHING_COMPANIES_STARTED';
export const FETCHING_COMPANIES_COMPLETED = 'FETCHING_COMPANIES_COMPLETED';
export const FETCHING_COMPANIES_FAILED = 'FETCHING_COMPANIES_FAILED';

export const FETCHING_COMPANY_PROJECTS_STARTED = 'FETCHING_COMPANY_PROJECTS_STARTED';
export const FETCHING_COMPANY_PROJECTS_COMPLETED = 'FETCHING_COMPANY_PROJECTS_COMPLETED';
export const FETCHING_COMPANY_PROJECTS_FAILED = 'FETCHING_COMPANY_PROJECTS_FAILED';

export const FETCHING_PROJECT_REPORTS_STARTED = 'FETCHING_PROJECT_REPORTS_STARTED';
export const FETCHING_PROJECT_REPORTS_COMPLETED = 'FETCHING_PROJECT_REPORTS_COMPLETED';
export const FETCHING_PROJECT_REPORTS_FAILED = 'FETCHING_PROJECT_REPORTS_FAILED';

export const FETCHING_PROJECT_REPORTS_MEDIA_STARTED = 'FETCHING_PROJECT_REPORTS_MEDIA_STARTED';
export const FETCHING_PROJECT_REPORTS_MEDIA_COMPLETED = 'FETCHING_PROJECT_REPORTS_MEDIA_COMPLETED';
export const FETCHING_PROJECT_REPORTS_MEDIA_FAILED = 'FETCHING_PROJECT_REPORTS_MEDIA_FAILED';