export const FETCH_PROJECT_ENROLLMENT_STARTED = 'FETCH_PROJECT_ENROLLMENT_STARTED';
export const FETCH_PROJECT_ENROLLMENT_COMPLETED = 'FETCH_PROJECT_ENROLLMENT_COMPLETED';
export const FETCH_PROJECT_ENROLLMENT_FAILED = 'FETCH_PROJECT_ENROLLMENT_FAILED';